version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      eslint:
        patterns:
          - '@typescript-eslint/*'
          - 'eslint*'
      react:
        patterns:
          - '@types/react-dom'
          - '@types/react'
          - 'react-dom'
          - 'react'
      react-helmet:
        patterns:
          - '@types/react-helmet'
          - 'react-helmet'
      stylelint:
        patterns:
          - 'stylelint*'
