name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ⏬ Checkout
        uses: actions/checkout@v2

      - name: ⚙️ Use Node.js (.nvmrc)
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version-file: ".nvmrc"

      - name: 🔋 Install
        run: npm ci

      - name: 🤖 Linting
        run: npm run lint

      - name: 🧪 Testing
        run: npm run test:ci

      - name: 🛠️ Building
        run: npm run build

      - name: 📊 Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
